# Site settings
title: McNeel Product Documentation
# email: brian@mcneel.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://help.mcneel.com" # the base hostname & protocol for your site
editMeOnGhBaseUrl: "mcneel/help-docs"

# To Generate a local Sitemap, remove the following 2 comments on the lines. And set safe: below to false.
#gems:
#  - jekyll-sitemap


# twitter_username: ""
github_username:  mcneel
simple_search: http://google.com/search
# Build settings
#markdown: redcarpet
encoding: utf-8

# If we decide that we want to use kramdown over redcarpet, syntax
# highlighting is performed by turning on the following options and
# including/running highlight.js (https://highlightjs.org/) at the
# top of pages that need it (probably just add to head.html)
markdown: kramdown
kramdown:
  input: GFM

#port: 4444

safe: safe


collections:
  - en
  - kr
　- jp

collections:
  en:
    output: true
  kr:
    output: true
  jp:
    output: true

defaults:
  -
    scope:
      path: ""
      type: en
    values:
      language: en
      productname: "Flamingo nXt"
      productpath: flamingo
      productversionpath: "5"
      layout: flamingo-toc-page

  -
    scope:
      path: "en/flamingo/5/help"
      type: en
    values:
      layout: flamingo-toc-page
      collectionname: "Help"
  -
    scope:
      path: "en/flamingo/5/guides"
    values:
      type: "guides_topic"
      layout: flamingo-toc-page
      collectionname: "Guides"
      sort: 1
  -
    scope:
      path: ""
      type: kr
    values:
      language: kr
      productname: "Flamingo nXt"
      productpath: flamingo
      productversionpath: "5"
      layout: flamingo-toc-page
  -
    scope:
      path: "kr/flamingo/5/help"
      type: kr
    values:
      doctype: "Help"
      layout: flamingo-toc-page
      collectionname: "도움말"
  -
    scope:
      path: "kr/flamingo/5/guides"
    values:
      doctype: "Guides"
      layout: flamingo-toc-page
      collectionname: "가이드"
  -
    scope:
      path: ""
      type: jp
    values:
      language: jp
      productname: "Flamingo nXt"
      productpath: flamingo
      productversionpath: "5"
      layout: flamingo-toc-page
  -
    scope:
      path: "jp/flamingo/5/help"
      type: jp
    values:
      doctype: "Help"
      layout: flamingo-toc-page
      collectionname: "ヘルプ"
  -
    scope:
      path: "jp/flamingo/5/guides"
    values:
      doctype: "Guides"
      layout: flamingo-toc-page
      collectionname: "ガイド"
