# Site settings
title: McNeel Product Documentation
# email: brian@mcneel.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://help.mcneel.com" # the base hostname & protocol for your site
editMeOnGhBaseUrl: "mcneel/help-docs"

# To Generate a local Sitemap, remove the following 2 comments on the lines. And set safe: below to false.
gems:
  - jekyll-sitemap


# twitter_username: ""
github_username:  mcneel
simple_search: http://google.com/search
# Build settings
#markdown: redcarpet
encoding: utf-8

# If we decide that we want to use kramdown over redcarpet, syntax
# highlighting is performed by turning on the following options and
# including/running highlight.js (https://highlightjs.org/) at the
# top of pages that need it (probably just add to head.html)
markdown: kramdown
kramdown:
  input: GFM

#port: 4444

safe: false

collections:
  en:
    output: true

defaults:
  -
    scope:
      path: ""
      type: en
    values:
      language: en
      productname: "Flamingo nXt"
      productpath: flamingo
      productversionpath: "5"
      layout: flamingo-toc-page
  -
    scope:
      path: "en/flamingo/5/help"
      type: en
    values:
      layout: flamingo-toc-page
      collectionname: "Help"
  -
    scope:
      path: "en/flamingo/5/guides"
    values:
      type: "guides_topic"
      layout: flamingo-guide-page
      collectionname: "Guides"
      sort: 1
