# Site settings
title: McNeel Product Documentation
# email: brian@mcneel.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://help.mcneel.com" # the base hostname & protocol for your site
editMeOnGhBaseUrl: "mcneel/help-docs"

# To Generate a local Sitemap, remove the following 2 comments on the lines. And set safe: below to false.
gems:
  - jekyll-sitemap


# twitter_username: ""
github_username:  mcneel
simple_search: http://google.com/search
# Build settings
#markdown: redcarpet
encoding: utf-8

# If we decide that we want to use kramdown over redcarpet, syntax
# highlighting is performed by turning on the following options and
# including/running highlight.js (https://highlightjs.org/) at the
# top of pages that need it (probably just add to head.html)
markdown: kramdown
kramdown:
  input: GFM

#port: 4444

safe: false

collections:
 - en
 - kr
 - jp
 - cn
 - de
 - es
 - fr
 - it
 - tw

collections:
  en:
    output: true
    permalink: /en/:path
  kr:
    output: true
    permalink: /kr/:path
  jp:
    output: true
    permalink: /jp/:path
  cn:
    output: true
    permalink: /cn/:path
  de:
    output: true
    permalink: /de/:path
  es:
    output: true
    permalink: /es/:path
  fr:
    output: true
    permalink: /fr/:path
  it:
    output: true
    permalink: /it/:path
  tw:
    output: true
    permalink: /tw/:path

defaults:
  - scope:
      path: ""
      type: en
    values:
      language: en
  - scope:
      path: "en"
    values:
      language: "en"
      lang: "en"
  - scope:
      path: "en/flamingo"
    values:
      productname: "Flamingo nXt"
      productpath: flamingo
      layout: flamingo-toc-page
  - scope:
      path: "_en/flamingo"
    values:
      productname: Flamingo nXt
      productpath: flamingo
      productversionpath: 5
  - scope:
      path: "_en/flamingo/5/help"
    values:
      productversionpath: "5"
      type: "help"
      layout: flamingo-toc-page
      collectionname: Help
  - scope:
      path: "_en/flamingo/5/guides"
    values:
      layout: flamingo-guide-page
      collectionname: Guides
  - scope:
      path: "_en/rhino"
      type: en
    values:
      collectionname: Guides
  - scope:
      path: "_en/zoo"
    values:
      productname: Zoo License Manager
      productpath: zoo
      layout: zoo-guide-page
      sort: 1
  - scope:
      path: "_en/zoo"
    values:
      productname: Zoo
      productpath: zoo
      productversionpath: 6
      type: guides_topic
      productname: Zoo License Manager
      keywords: ['zoo', 'rhinoceros', 'license', 'manager']
      layout: zoo-toc-page
  - scope:
      path: "_en/zoo/6/help"
    values:
      layout: zoo-toc-page
      collectionname: Help
      type: help
  - scope:
      path: "_en/zoo/6/guides"
    values:
      layout: zoo-guide-page
      collectionname: Guides
  - scope:
      path: ""
      type: kr
    values:
      language: kr
      layout: flamingo-toc-page
  - scope:
      path: "_kr/flamingo"
    values:
      productname: Flamingo nXt
      productpath: flamingo
      productversionpath: 5
  - scope:
      path: "_kr/flamingo/5/help"
    values:
      layout: flamingo-toc-page
      collectionname: 도움말
  - scope:
      path: "_kr/flamingo/5/guides"
    values:
      layout: flamingo-guide-page
      collectionname: 가이드
  - scope:
      path: ""
      type: jp
    values:
      language: jp
      productname: "Flamingo nXt"
      productpath: flamingo
      productversionpath: "5"
      layout: flamingo-toc-page
  - scope:
      path: "jp/flamingo/5/help"
      type: jp
    values:
      doctype: "Help"
      layout: flamingo-toc-page
      collectionname: "ヘルプ"
  - scope:
      path: "jp/flamingo/5/guides"
    values:
      doctype: "Guides"
      layout: flamingo-guide-page
      collectionname: "ガイド"
  - scope:
      path: ""
      type: de
    values:
      language: de
      productname: "Flamingo nXt"
      productpath: flamingo
      productversionpath: "5"
      layout: flamingo-toc-page
  - scope:
      path: "de/flamingo/5/help"
      type: de
    values:
      doctype: "Help"
      layout: flamingo-toc-page
      collectionname: "Hilfe"
  - scope:
      path: "de/flamingo/5/guides"
    values:
      doctype: "Guides"
      layout: flamingo-guide-page
      collectionname: "Anleitungen"
  - scope:
      path: ""
      type: cn
    values:
      language: cn
      productname: "Flamingo nXt"
      productpath: flamingo
      productversionpath: "5"
      layout: flamingo-toc-page
  - scope:
      path: "cn/flamingo/5/help"
      type: cn
    values:
      doctype: "Help"
      layout: flamingo-toc-page
      collectionname: "Help"
  - scope:
      path: "cn/flamingo/5/guides"
    values:
      doctype: "Guides"
      layout: flamingo-guide-page
      collectionname: "Guides"
  - scope:
      path: ""
      type: es
    values:
      language: es
      productname: "Flamingo nXt"
      productpath: flamingo
      productversionpath: "5"
      layout: flamingo-toc-page
  - scope:
      path: "es/flamingo/5/help"
      type: es
    values:
      doctype: "Help"
      layout: flamingo-toc-page
      collectionname: "Ayuda"
  - scope:
      path: "es/flamingo/5/guides"
    values:
      doctype: "Guides"
      layout: flamingo-guide-page
      collectionname: "Guías"
  - scope:
      path: ""
      type: fr
    values:
      language: fr
      productname: "Flamingo nXt"
      productpath: flamingo
      productversionpath: "5"
      layout: flamingo-toc-page
  - scope:
      path: "fr/flamingo/5/help"
      type: fr
    values:
      doctype: "Help"
      layout: flamingo-toc-page
      collectionname: "Aide"
  - scope:
      path: "fr/flamingo/5/guides"
    values:
      doctype: "Guides"
      layout: flamingo-guide-page
      collectionname: "Guides"
  - scope:
      path: ""
      type: it
    values:
      language: it
      productname: "Flamingo nXt"
      productpath: flamingo
      productversionpath: "5"
      layout: flamingo-toc-page
  - scope:
      path: "it/flamingo/5/help"
      type: it
    values:
      doctype: "Help"
      layout: flamingo-toc-page
      collectionname: "Aiuti"
  - scope:
      path: "it/flamingo/5/guides"
    values:
      doctype: "Guides"
      layout: flamingo-guide-page
      collectionname: "Guide"
  - scope:
      path: ""
      type: tw
    values:
      language: tw
      productname: "Flamingo nXt"
      productpath: flamingo
      productversionpath: "5"
      layout: flamingo-toc-page
  - scope:
      path: "tw/flamingo/5/help"
      type: tw
    values:
      doctype: "Help"
      layout: flamingo-toc-page
      collectionname: "Help"
  - scope:
      path: "tw/flamingo/5/guides"
    values:
      doctype: "Guides"
      layout: flamingo-guide-page
      collectionname: "Guides"

